services:
  - type: web
    name: kastack-chatbot
    runtime: python
    region: oregon
    autoDeployTrigger: commit
    healthCheckPath: /health
    buildCommand: pip install -r requirements.txt && python -m nltk.downloader punkt stopwords vader_lexicon averaged_perceptron_tagger
    startCommand: cd backend && gunicorn --preload -w 1 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
